set(btstack_core_srcs
    src/ad_parser.c
    src/ble/att_db.c # GATT_SERVER
    src/ble/att_db_util.c
    src/ble/att_dispatch.c # ATT
    src/ble/att_server.c # GATT_SERVER
    src/ble/gatt-service/ancs_client.c
    src/ble/gatt-service/battery_service_client.c
    src/ble/gatt-service/battery_service_server.c
    src/ble/gatt-service/cycling_power_service_server.c
    src/ble/gatt-service/cycling_speed_and_cadence_service_server.c
    src/ble/gatt-service/device_information_service_client.c
    src/ble/gatt-service/device_information_service_server.c
    src/ble/gatt-service/heart_rate_service_server.c
    src/ble/gatt-service/hids_client.c
    src/ble/gatt-service/hids_device.c
    src/ble/gatt-service/mesh_provisioning_service_server.c
    src/ble/gatt-service/mesh_proxy_service_server.c
    src/ble/gatt-service/nordic_spp_service_server.c
    src/ble/gatt-service/scan_parameters_service_client.c
    src/ble/gatt-service/scan_parameters_service_server.c
    src/ble/gatt-service/ublox_spp_service_server.c
    src/ble/gatt_client.c
    src/ble/le_device_db_memory.c
    src/ble/le_device_db_tlv.c
    src/ble/sm.c
    src/btstack_audio.c
    src/btstack_base64_decoder.c
    src/btstack_crypto.c
    src/btstack_hid.c
    src/btstack_hid_parser.c
    src/btstack_linked_list.c
    src/btstack_linked_queue.c
    src/btstack_memory.c
    src/btstack_memory_pool.c
    src/btstack_resample.c
    src/btstack_ring_buffer.c
    src/btstack_run_loop.c
    src/btstack_run_loop_base.c
    src/btstack_slip.c
    src/btstack_tlv.c
    src/btstack_tlv_none.c
    src/btstack_uart_slip_wrapper.c
    src/btstack_util.c
    src/classic/a2dp_sink.c
    src/classic/a2dp_source.c
    src/classic/avdtp.c
    src/classic/avdtp_acceptor.c
    src/classic/avdtp_initiator.c
    src/classic/avdtp_sink.c
    src/classic/avdtp_source.c
    src/classic/avdtp_util.c
    src/classic/avrcp.c
    src/classic/avrcp_browsing.c
    src/classic/avrcp_browsing_controller.c
    src/classic/avrcp_browsing_target.c
    src/classic/avrcp_controller.c
    src/classic/avrcp_media_item_iterator.c
    src/classic/avrcp_target.c
    src/classic/bnep.c
    src/classic/btstack_cvsd_plc.c
    src/classic/btstack_link_key_db_memory.c
    src/classic/btstack_link_key_db_static.c
    src/classic/btstack_link_key_db_tlv.c
    #src/classic/btstack_sbc_decoder_bluedroid.c
    #src/classic/btstack_sbc_encoder_bluedroid.c
    #src/classic/btstack_sbc_plc.c
    src/classic/device_id_server.c
    src/classic/gatt_sdp.c
    src/classic/goep_client.c
    src/classic/hfp.c
    src/classic/hfp_ag.c
    src/classic/hfp_gsm_model.c
    src/classic/hfp_hf.c
    src/classic/hfp_msbc.c
    src/classic/hid_device.c
    src/classic/hid_host.c
    src/classic/hsp_ag.c
    src/classic/hsp_hs.c
    src/classic/obex_iterator.c
    src/classic/obex_message_builder.c
    src/classic/pan.c
    #src/classic/pbap_client.c
    src/classic/rfcomm.c
    src/classic/sdp_client.c
    src/classic/sdp_client_rfcomm.c
    src/classic/sdp_server.c
    src/classic/sdp_util.c
    src/classic/spp_server.c
    src/hci.c
    src/hci_cmd.c
    src/hci_dump.c
    src/hci_transport_em9304_spi.c
    src/hci_transport_h4.c
    src/hci_transport_h5.c
    src/l2cap.c
    src/l2cap_signaling.c

    # 3rd Party
    3rd-party/micro-ecc/uECC.c
    3rd-party/rijndael/rijndael.c
    )

set(btstack_libusb_srcs
    platform/libusb/hci_transport_h2_libusb.c
    )

set(btstack_posix_srcs
    #platform/posix/btstack_audio_portaudio.c
    platform/posix/btstack_link_key_db_fs.c
    #platform/posix/btstack_network_posix.c
    platform/posix/btstack_run_loop_posix.c
    #platform/posix/btstack_sco_transport_posix_i2s_test_bridge.c
    platform/posix/btstack_stdin_posix.c
    platform/posix/btstack_tlv_posix.c
    platform/posix/btstack_uart_posix.c
    platform/posix/hci_dump_posix_fs.c
    platform/posix/hci_dump_posix_stdout.c
    platform/posix/le_device_db_fs.c
    platform/posix/wav_util.c
    )
